### ISSUE TITLE
Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@85ca854) but could not find and invoke the GeneratedPluginRegistrant.

### ISSUE THREAD

**Issue by rbimrose** [fluttercommunity/flutter_workmanager#214]
I am getting following error/warning, and not able do any operation. Please help to resolve.

**Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@85ca854) but could not find and invoke the GeneratedPluginRegistrant.**

**Comment by rbimrose** [comment]
**keyboard_visibility: ^0.5.6** plugin is creating this error. Is it a error from **keyboard_visibility or workmanager: 0.2.2 ?**

**Comment by 2math** [comment]
try with flutter_keyboard_visibility
on my side it works with :
```
  flutter_keyboard_visibility: ^4.0.2

  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager
      ref: 1c4e162ea4e71855856fb9e55a1545b3dae9a25d
```
