### ISSUE TITLE
🐞After upgrading SDK to Flutter 3.0.5 I get this error: BasicMessageChannel: Parameter messenger must not be null.

### ISSUE THREAD

**Issue by alirizadagli** [fluttercommunity/flutter_workmanager#414]
DEBUG CONSOLE:
I/WM-WorkerWrapper(10976): Worker result SUCCESS for Work [ id=9fe5a666-2857-4939-9b6a-1d4d58cc9b01, tags={ be.tramckrijte.workmanager.BackgroundWorker } ]
E/BasicMessageChannel#(10976): Parameter messenger must not be null.
D/AndroidRuntime(10976): Shutting down VM
E/AndroidRuntime(10976): FATAL EXCEPTION: main
E/AndroidRuntime(10976): Process: com.example.error, PID: 10976
E/AndroidRuntime(10976): java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
E/AndroidRuntime(10976): 	at io.flutter.plugin.common.BasicMessageChannel.setMessageHandler(BasicMessageChannel.java:132)
E/AndroidRuntime(10976): 	at io.flutter.plugins.firebase.auth.GeneratedAndroidFirebaseAuth$MultiFactorUserHostApi$-CC.setup(GeneratedAndroidFirebaseAuth.java:358)
E/AndroidRuntime(10976): 	at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin.onDetachedFromEngine(FlutterFirebaseAuthPlugin.java:131)
E/AndroidRuntime(10976): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:270)
E/AndroidRuntime(10976): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:280)
E/AndroidRuntime(10976): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:288)
E/AndroidRuntime(10976): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:121)
E/AndroidRuntime(10976): 	at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:425)
E/AndroidRuntime(10976): 	at be.tramckrijte.workmanager.BackgroundWorker.stopEngine$lambda-2(BackgroundWorker.kt:137)
E/AndroidRuntime(10976): 	at be.tramckrijte.workmanager.BackgroundWorker.$r8$lambda$u5fs2CPxJ29Hdjbap5WYUt2tGrg(Unknown Source:0)
E/AndroidRuntime(10976): 	at be.tramckrijte.workmanager.BackgroundWorker$$ExternalSyntheticLambda1.run(Unknown Source:2)
E/AndroidRuntime(10976): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(10976): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(10976): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(10976): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(10976): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/AndroidRuntime(10976): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10976): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(10976): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
I/Process (10976): Sending signal. PID: 10976 SIG: 9
Lost connection to device.
Exited (sigterm)

FLUTTER DOCTOR -v

[✓] Flutter (Channel stable, 3.0.5, on Ubuntu 20.04.4 LTS 5.15.0-41-generic, locale
    tr_TR.UTF-8)
    • Flutter version 3.0.5 at /home/ali/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (10 gün önce), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /home/ali/Android/Sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • ANDROID_HOME = /home/ali/Android/Sdk
    • Java binary at: /snap/android-studio/123/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.2)
    • Android Studio at /snap/android-studio/123/android-studio
    • Flutter plugin version 69.0.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 32)
      (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Ubuntu 20.04.4 LTS
      5.15.0-41-generic
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome
      103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by Paitomax** [comment]
I also got this error, but the error only occurs with these firebase versions (with MFA):
```yaml
  firebase_core: ^1.20.0
  firebase_auth: ^3.5.0
  firebase_analytics: ^9.2.1
  firebase_crashlytics: ^2.8.6
  firebase_performance: ^0.8.2+1
  firebase_remote_config: ^2.0.13
  firebase_messaging: ^12.0.1
  firebase_in_app_messaging: ^0.6.0+20
  firebase_dynamic_links: ^4.3.3
  firebase_database: ^9.0.20
```

---

Does not occur with previous firebase version (without MFA):
```yaml
  firebase_core: ^1.19.2
  firebase_auth: ^3.4.2
  firebase_analytics: ^9.2.0
  firebase_crashlytics: ^2.8.5
  firebase_performance: ^0.8.2
  firebase_remote_config: ^2.0.12
  firebase_messaging: ^12.0.0
  firebase_in_app_messaging: ^0.6.0+19
  firebase_dynamic_links: ^4.3.2
  firebase_database: ^9.0.19
```
